# pagescms.config.yml
backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "posts"
    label: "পোস্টসমূহ"
    folder: "_data/posts.json"
    format: "json"
    create: true
    delete: true
    fields:
      - { label: "শিরোনাম", name: "title", widget: "string" }
      - { label: "বিবরণ", name: "description", widget: "text" }
      - { 
          label: "ক্যাটাগরি", 
          name: "category", 
          widget: "select", 
          options: ["skins", "mods", "apk", "codename"] 
        }
      - { 
          label: "ছবির লিংক", 
          name: "images", 
          widget: "list", 
          field: { label: "ছবি", name: "url", widget: "string" } 
        }
      - { label: "নাম", name: "name", widget: "string" }
      - { label: "সাপোর্টেড ভার্সন", name: "supported", widget: "string" }
      - { label: "সাইজ", name: "size", widget: "string" }
      - { label: "প্রস্তুতকারক", name: "creator", widget: "string" }
      - { label: "ডাউনলোড লিংক", name: "download", widget: "string" }
      - { label: "ভিডিও টিউটোরিয়াল", name: "videoUrl", widget: "string", required: false }
      - { label: "তারিখ", name: "date", widget: "datetime" }
